using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.Guidebook;
using Robust.Shared.Prototypes;
using Content.Shared._Eclipse.SelfShipyard.BUI;

namespace Content.Client._Eclipse.SelfShipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class OwnedVesselRow : PanelContainer
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    public OwnedVesselVisibleRecord? Vessel;
    public OwnedVesselRow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
