using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Eclipse.Chemistry.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LabelledContentBoxNoEject : BoxContainer
    {
        public string? LabelText { get => Label.Text; set => Label.Text = value; }

    }
}
