# HASH: 7d45660eefa90b6e51185f652362ce8300b385fe4f5869f490d903faeef71d71
ent-ClothingUniformRandomPunkBase = { "" }
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visuals
# HASH: 9661196109dc4f310c98aad1077f382f6fdaf0e9b1b014919f8c57295c43e7dc
ent-ClothingUniformRandomPunkCroptop = панковский комбинезон с укороченным топом
    .desc = Генерируется нейронными сетями на основе последних модных тенденций.
    .suffix = Случайный цвет
# HASH: daa04266589d3c1c5bb50ecf73c1c8a1f1ed99775033f8ae5c18d40eed90cb16
ent-ClothingUniformRandomPunkTanktop = панковский комбинезон
    .desc = { ent-ClothingUniformRandomPunkCroptop.desc }
# HASH: 755376bf6e19ad840b45cba9893340348588c9bfa373904e53bb654d429d6f23
ent-ClothingUniformRandomArmlessNoSkirt = красочный панковский комбинезон
    .desc = { ent-ClothingUniformRandomPunkCroptop.desc }
# HASH: 4a3e6bcc7f62033a2f5d56e2e9139ae8b4d848a246b78c0fc04396b0818acd35
ent-ClothingUniformRandomPunkCroptopShorts = панковский комбинезон с укороченным топом
    .desc = { ent-ClothingUniformRandomPunkCroptop.desc }
    .suffix = Случайный цвет
# HASH: f233d92c58f7edce879e342decb8bcad4a22997c5a6b39b0ff7c71ec66558e13
ent-ClothingUniformRandomPunkTanktopShorts = панковский комбинезон
    .desc = { ent-ClothingUniformRandomPunkCroptop.desc }
# HASH: fe9a3d66a9588c761ee29b9de0adf488a821e01bb8748e0801e6e9c36486ddc7
ent-ClothingUniformRandomPunkPantsOnly = punk pants
    .desc = { ent-ClothingUniformRandomPunkBase.desc }
# HASH: 0e917d6c9e7d242e52092fa11d23e09ae97862af70141a8c57b88cc339d71967
ent-ClothingUniformRandomPunkShortsOnly = punk shorts
    .desc = { ent-ClothingUniformRandomPunkBase.desc }
