# HASH: 379e52b4db5037bc0edb0c37c2c0cf1ecb3530110c6fbf4d06beeb400be0c16f
ent-ClothingUniformRandomPunkBase = { ent-BaseItem }
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visuals
# HASH: 9661196109dc4f310c98aad1077f382f6fdaf0e9b1b014919f8c57295c43e7dc
ent-ClothingUniformRandomPunkCroptop = панковский комбинезон с укороченным топом
    .desc = Генерируется нейронными сетями на основе последних модных тенденций.
# HASH: 1966c0c2f8a5ab7610e7712f1b78d425e84f4f702c5934c44a0a1fec6c9731e8
ent-ClothingUniformRandomPunkTanktop = панковский комбинезон
    .desc = { ent-ClothingUniformRandomPunkCroptop.desc }
# HASH: 4a81884695c894827939eed036e925768ad93cea5c99694f34067b0df3495bea
ent-ClothingUniformRandomArmlessNoSkirt = красочный панковский комбинезон
    .desc = { ent-ClothingUniformRandomPunkCroptop.desc }
# HASH: 4a3e6bcc7f62033a2f5d56e2e9139ae8b4d848a246b78c0fc04396b0818acd35
ent-ClothingUniformRandomPunkCroptopShorts = панковский комбинезон с укороченным топом
    .desc = { ent-ClothingUniformRandomPunkBase.desc }
# HASH: 58bb1672579c8ac9bb1d66a142d34abf5b22c8ce0d02f40654f01b6e7724432f
ent-ClothingUniformRandomPunkTanktopShorts = панковский комбинезон
    .desc = { ent-ClothingUniformRandomPunkCroptopShorts.desc }
# HASH: fe9a3d66a9588c761ee29b9de0adf488a821e01bb8748e0801e6e9c36486ddc7
ent-ClothingUniformRandomPunkPantsOnly = punk pants
    .desc = { ent-ClothingUniformRandomPunkBase.desc }
# HASH: 0e917d6c9e7d242e52092fa11d23e09ae97862af70141a8c57b88cc339d71967
ent-ClothingUniformRandomPunkShortsOnly = punk shorts
    .desc = { ent-ClothingUniformRandomPunkBase.desc }
