[net]
max_connections = 1024
pvs_range = 20.0
pvs_priority_range = 30.0
tickrate = 60

[game]
maxplayers = 150
soft_max_players = 100
hostname = "🌒 Project Eclipse - ФРОНТИР! [TTS][18+] 🌒"
desc = "🌒Начни свое путешествие на секторе ЭКЛИПС прямо сейчас!\n🌒Система TTS 200+ голосов, выбери себе голос по вкусу!\n🌒Уникальная система сохранения своего шаттла, построй свой шаттл мечты!\n\n💎На сервере средний уровень отыгрыша РП.\n💎Смены идут по 72 часа, достаточно для воплощения ваших фантазий!\n💎Множество своих уникальных систем, улучшений и разработок!\n💎Постройте шаттл своей мечты, ограничение только ваша фантазия!\n💎Отзывчивая и дружелюбная администрация!\n💎Наш сервер работает на сверхмощном железе со стабильным тикрейтом в 60!\n💎Полная локализация и постоянные обновления!\n"
cryo_sleep_rejoining = true
defaultpreset = "nfadventure"

[shuttle]
auto_call_time = 4320
arrivals = false
emergency_dock_time = 360 # an extra 2 minutes over the default
emergency_transit_time_min = 300
auto_call_extension_time = 45
emergency_early_launch_allowed = false
shipyard_base_sell_rate = 0.5

[rules]
time = 60

[atmos]
space_wind = true

[viewport]
minimum_width = 15
maximum_width = 26

[ic]
flavor_text = true
punctuation = true

[worldgen]
enabled = true

[replay]
client_recording_enabled = false

[server]
id = "frontier_main"
rules_file = "FrontierRuleset"

[infolinks]
bug_report = "https://github.com/Project-Eclipse-SS14/Eclipse-New-Frontier/issues/new/choose"
discord = "https://discord.gg/5J9Q8WuJFd"
#forum = ""
github = "https://github.com/Project-Eclipse-SS14/Eclipse-New-Frontier"
patreon = ""
website = "https://boosty.to/project_eclipse"
#wiki = ""
#appeal = ""

[nf14]
respawn.time = 300.0
uncryo.maxtime = 604800.0 # 10 days

[eclipse]
restart_when_server_empty = false
start_round_with_no_players = true
shuttle_auto_call_enabled = false

[biomass]
easy_mode = false # reclaimer can work on soul-ful bodies, mrp server

[control]
storage_limit = 3

[discord]
rich_main_icon_id = "https://shorturl.at/nHmHm"

[chat]
max_message_length = 3000

[salvage]
expedition_duration = 2400 # 40 minutes