# HASH: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
ent-ClothingHeadHelmetBase = { "" }
    .desc = { "" }
# HASH: 24e9411bd15efeaaedb7c5719a5e6b6a0532e5317f3bc1f9f3e0ce533fb125fb
ent-ClothingHeadHelmetBasic = helmet
    .desc = Standard security gear. Protects the head from impacts.
# HASH: 08a1bf6cb60c667d6f45780c1d9696158c75391788cedff16e2c0df0344c8ff5
ent-ClothingHeadHelmetMercenary = mercenary helmet
    .desc = The combat helmet is commonly used by mercenaries, is strong, light and smells like gunpowder and the jungle.
# HASH: b7ee95c883432cd1a69a96b0fd3ed048dfdc20c2a008ce5790f5da066c7db552
ent-ClothingHeadHelmetSwat = SWAT helmet
    .desc = An extremely robust helmet, commonly used by paramilitary forces. This one has the Nanotrasen logo emblazoned on the top.
# HASH: 3bb8b45c24df44a44a999081b01bd60f97db642c4d6235adecd76a197945c91e
ent-ClothingHeadHelmetSwatSyndicate = SWAT helmet
    .desc = An extremely robust helmet, commonly used by paramilitary forces. It is adorned in a nefarious red and black stripe pattern.
    .suffix = Syndicate
# HASH: db4e721f4838e69497f5edd2d56f01d3380cad93d7a42f53dca005c3ebae60df
ent-ClothingHeadHelmetRiot = light riot helmet
    .desc = It's a helmet specifically designed to protect against close range attacks.
# HASH: 9b5610b9ab1b181c5d2d8961af9d861aa1b5d4848ec96a0a31a7b72a3b14eb4a
ent-ClothingHeadHelmetBombSuit = bombsuit helmet
    .desc = A heavy helmet designed to withstand the pressure generated by a bomb and any fragments the bomb may produce.
# HASH: 181fe74988819d21306efdea4aafd9affd58b16f07704705a204b2a3e260d4f7
ent-ClothingHeadHelmetJanitorBombSuit = janitorial bombsuit helmet
    .desc = A heavy helmet designed to withstand explosions formed from reactions between chemicals.
# HASH: 5dc4d02f86e8e193ef2fe03cf1b7bc4fdcddbfddfae8d63d1afa71225c470a3c
ent-ClothingHeadHelmetCult = cult helmet
    .desc = A robust, evil-looking cult helmet.
# HASH: 7c9ce7da8d285344567b794c9a16540b87537d0178e7253cb3d71d337237f82c
ent-ClothingHeadHelmetSpaceNinja = space ninja helmet
    .desc = What may appear to be a simple black garment is in fact a highly sophisticated nano-weave helmet. Standard issue ninja gear.
# HASH: e1b8b507d3859f390f9c4e1a4639b3818f9f953ae3c255e85203310c0414d79b
ent-ClothingHeadHelmetTemplar = templar helmet
    .desc = DEUS VULT!
# HASH: 6e42aff3d3fbd0e86281d5ab129caa6af690bdb891c5463d7e5eabf8922a41d6
ent-ClothingHeadHelmetThunderdome = thunderdome helmet
    .desc = Let the battle commence!
# HASH: 3e78161cd8e275296cbfbd48a636cb1daf49071030afdd9891fed1b4dc2932a5
ent-ClothingHeadHelmetWizardHelm = wizard helm
    .desc = Strange-looking helmet that most certainly belongs to a real magic user.
# HASH: 44a6329200c2b74255799936dafe44404910034b6e6a9a38c8be1591e46bb668
ent-ClothingHeadHelmetFire = fire helmet
    .desc = An atmos tech's best friend. Provides some heat resistance and looks cool.
# HASH: 3ca30d7aea6318e38e2fd9d57a5c0dc199b71fd1030a3bec435c18b459825bcd
ent-ClothingHeadHelmetAtmosFire = atmos fire helmet
    .desc = An atmos fire helmet, able to keep the user cool in any situation.
# HASH: fa0d08ccbbafbeed1cd2aa08bafee46806dccd27c265ebf8a97d6e0bad64977b
ent-ClothingHeadHelmetLing = chitinous helmet
    .desc = An all-consuming chitinous mass of armor.
# HASH: 6a2acbbc04f2bab72e30515836a6aa3716943f6d4d782dba4ce4bf21b2eee6f1
ent-ClothingHeadHelmetERTLeader = ERT leader helmet
    .desc = An in-atmosphere helmet worn by the leader of a Nanotrasen Emergency Response Team. Has blue highlights.
# HASH: 535a5a4fa1f61d4d61357614c6efb1cc26e5196f922e788471209ed7f9892de7
ent-ClothingHeadHelmetERTSecurity = ERT security helmet
    .desc = An in-atmosphere helmet worn by security members of the Nanotrasen Emergency Response Team. Has red highlights.
# HASH: 78b7dbff69060fdb07b432ef502300d5c9934f0cf7bf917bb121eb852ab31d00
ent-ClothingHeadHelmetERTMedic = ERT medic helmet
    .desc = An in-atmosphere helmet worn by medical members of the Nanotrasen Emergency Response Team. Has white highlights.
# HASH: 7b2a6480ee10749493c29ab5c6700230b0e14ef33d1e0aff7c49515298d5469d
ent-ClothingHeadHelmetERTEngineer = ERT engineer helmet
    .desc = An in-atmosphere helmet worn by engineering members of the Nanotrasen Emergency Response Team. Has orange highlights.
# HASH: 3baf1269b0a45e585316d3aa6d222cea2760ad87df01a80ba803330cfdbb9cc7
ent-ClothingHeadHelmetERTJanitor = ERT janitor helmet
    .desc = An in-atmosphere helmet worn by janitorial members of the Nanotrasen Emergency Response Team. Has dark purple highlights.
# HASH: 87b4a3b245485ad0282f6fa54ebfc9c4fc8a4ab8e0c0c1fe837a12878be2720d
ent-ClothingHeadHelmetRaid = syndicate raid helmet
    .desc = An armored helmet for use with the syndicate raid suit. Very stylish.
# HASH: 032c1cebe7ec1c3667cba823b3c34b47333feb403fec03ad029693d617fa25ac
ent-ClothingHeadHelmetBone = bone helmet
    .desc = Cool-looking helmet made of skull of your enemies.
# HASH: 96f027f8afa2e41ecf30ef68167d72bb9db4dfa0eb10739a1d4a6e3eb7359493
ent-ClothingHeadHelmetPodWars = ironclad II helmet
    .desc = An ironclad II helmet, a relic of the pod wars.
# HASH: cbfa27476f8fa6067ea53d1a14628381d580fcd0f0a0562c0dac34503fc76152
ent-ClothingHeadHelmetJustice = justice helm
    .desc = Advanced security gear. Protects the station from ne'er-do-wells.
# HASH: 60b9ce539317d4921edb21eb2245f80a42ee6dea876dc463e809da6dbfa7818b
ent-ClothingHeadHelmetJusticeEmpty = { ent-ClothingHeadHelmetJustice }
    .desc = { ent-ClothingHeadHelmetJustice.desc }
    .suffix = Empty
# HASH: 967649e8202aec7b5c1376795ac0a7cc77acf3f8758d3003b9c4b358d529b663
ent-ActionToggleJusticeHelm = Toggle Justice Helm
    .desc = Toggles the justice helm on and off.
