# HASH: a1046aacdad7875630753c479b5f2b86d0fc8b7d7370ed430e2cbdb96a8684ea
ent-ClothingUniformRandom = { ent-ClothingUniformBase }
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visual
# HASH: 1ef9a87c40bb78a837a4f027528a4d0218606ee8c12fff709215e4c8da05fa59
ent-ClothingRandomSpawner = random colorful outfit
    .desc = { ent-ClothingUniformRandom.desc }
# HASH: 7e6b453e2218a49ed1739ff912df989a2977b52d9718490c2dd8b88d188fe24d
ent-ClothingUniformRandomArmless = colorful sleeveless top and pants
    .desc = { ent-ClothingUniformRandom.desc }
# HASH: 4693e6d04595edea4a74b61536a91574276f366b3c1edf10b0a79a0cb3606130
ent-ClothingUniformRandomStandard = colorful top and pants
    .desc = { ent-ClothingUniformRandom.desc }
# HASH: dc8e53ef8cdb57170a41b17ce7e43ce4fad3a76f54b2522f44423559c19d1a17
ent-ClothingUniformRandomBra = colorful bra and pants
    .desc = { ent-ClothingUniformRandom.desc }
# HASH: 1c720590e4496f6bc2efd69fa01e27b082d4edeb658d0405e5eb1b6faf923978
ent-ClothingUniformRandomShorts = colorful pants
    .desc = { ent-ClothingUniformRandom.desc }
# HASH: 838ad5702b3c39cdf20e67b9bce0c28d229aaf1737a79e904c566e8f56f1856b
ent-ClothingUniformRandomShirt = colorful patterned top and pants
    .desc = { ent-ClothingUniformRandom.desc }
