# HASH: ea9fb4d3404cdd41e27d6f6392b10d99656f0b88db53a6971699fff0fc3e9a82
ent-ClothingOuterSuitBomb = bomb suit
    .desc = A heavy suit designed to withstand the pressure generated by a bomb and any fragments the bomb may produce.
# HASH: 1b6c4a7e1ef320c569dc5ed76679a3b68be9f3f9bb808e6ed553df45ddc16a05
ent-ClothingOuterSuitJanitorBomb = janitorial bomb suit
    .desc = A heavy helmet designed to withstand explosions formed from reactions between chemicals.
# HASH: 7a605baf910bdbb91df4f9c923f1a9d0cb3c7620765265312e3f8482070b3ad0
ent-ClothingOuterSuitFire = fire suit
    .desc = A suit that helps protect against hazardous temperatures.
# HASH: 4f3393f34cf0c386c85cb77ef6f523788d15d04388edad59cfb204248cf0ea56
ent-ClothingOuterSuitAtmosFire = atmos fire suit
    .desc = An expensive firesuit that protects against even the most deadly of station fires. Designed to protect even if the wearer is set aflame.
# HASH: 8d63cb8db30aed248affa0614042aba19cba58ac1c5133446cb00d5c8b40befb
ent-ClothingOuterSuitRad = radiation suit
    .desc = A suit that protects against radiation. The label reads, 'Made with lead. Please do not consume insulation.'
# HASH: d4757b5e52489a283cca40584f5f9e54ed6169bc0791f22135c984b9d7cadd60
ent-ClothingOuterSuitSpaceNinja = space ninja suit
    .desc = This black technologically advanced, cybernetically-enhanced suit provides many abilities like invisibility or teleportation.
# HASH: 20bac069b2ce3ec0bda4f92e917edfaec3953a29891b431e615e03fc656dc34b
ent-ClothingOuterSuitChicken = chicken suit
    .desc = Bok bok bok!
# HASH: 229514065a1a8b056aa760c9f9df3662229b7d7636f08bf3173fffa062ea52c9
ent-ClothingOuterSuitShrineMaiden = shrine maiden outfit
    .desc = Makes you want to go deal with some troublesome youkai.
# HASH: be706cebb1dbe0628f19b4721b7987ed71967387949104d46568a1e0e547bebc
ent-ClothingOuterSuitWitchRobes = witch robes
    .desc = Magic is all about the spell power, ZE!
# HASH: 5b03ca95b9f2d323b3986a1a0e876a837de7c49c9f5dd15ee7279c133cc90ab0
ent-ClothingOuterSuitMonkey = monkey suit
    .desc = A suit that looks like a primate.
# HASH: 19ec76488b2c08954f03161f0c0b34e3e0e0149ae271dd30f926c6c2acf722cc
ent-ClothingOuterSuitIan = ian suit
    .desc = Who's a good boy?
# HASH: f3cdcd7172ea8a12155a0f54feaacf5a39f02475529c902cbbd7e913e2458f70
ent-ClothingOuterSuitCarp = carp suit
    .desc = A special suit that makes you look just like a space carp, if your eyesight is bad.
# HASH: e0fcab330288c7235bb849ab2cbe943be321a26b74a3d74b396c2719b4009bb7
ent-ClothingOuterHardsuitCarp = { ent-ClothingOuterSuitCarp }
    .desc = { ent-ClothingOuterSuitCarp.desc }
    .suffix = Hardsuit, DO NOT MAP
