name: "Labels: Branch staging"

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'staging'

jobs:
  add_label:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Branch: Staging"
